version: 2.1
executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:3.0.2-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: password
      - image: circleci/mysql:8.0.26
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_ROOT_PASSWORD: password
jobs:
  rubocop:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Copy Environments
          command: cp ./api/.env.default ./api/.env
      - run:
          name: bundle install
          command: |
            cd api
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~repo/api/vendor/bundle
      - run:
          name: Run rubocop
          command: |
            cd api
            bundle exec rubocop --parallel
  rspec:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Copy Environments
          command: cp ./api/.env.default ./api/.env
      - run:
          name: bundle install
          command: |
            cd api
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~repo/api/vendor/bundle
      - run:
          name: wait mysql
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: create database
          command: |
            cd api
            bundle exec rake db:create
      - run:
          name: migrate
          command: |
            cd api
            bundle exec rails db:migrate
      - run:
          name: Rspec
          command: |
            cd api
            bundle exec rspec
      - store_test_results:
          path: ./api/tmp/test-results

workflows:
  version: 2
  main:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
