inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.1
  TargetRailsVersion: 6.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config.ru'
    - 'Rakefile'

# 日本語コメント OK
Style/AsciiComments:
  Enabled: false

# missing top-level class documentation comment 抑制
Documentation:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'app/views/**/*.jbuilder'
    - 'lib/tasks/dev.rake'

Layout:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Lint:
  Enabled: true

Naming:
  Enabled: true

# メソッド名の先頭にsetやgetを使用しない
Naming/AccessorMethodName:
  Enabled: false

# メソッド名の先頭にisやhasを使用しない
Naming/PredicateName:
  Enabled: false

Security:
  Enabled: true

# and, or でなく &&, || を使うように
Style/AndOr:
  Enabled: true

# 文字列だけのリテラルを括るのにシングルクォートを使用する
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Hashの最後の要素の末尾にカンマをつける
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Arrayの最後の要素の末尾にカンマをつける
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Ruby3系にスムーズに移行するためにtrueにしておく
Style/FrozenStringLiteralComment:
  Enabled: true

# %記法の配列の括弧の種類を強制する
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()
    '%W': ()

require: rubocop-rails
Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

# renderで返すstatusをステータスコードで書く
Rails/HttpStatus:
  EnforcedStyle: numeric

# DateでなくTimeWithZoneの使用を強制
Rails/Date:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: false
